name: Build and Release (Beta)

permissions:
  contents: write

on:
  push:
    tags:
      - 'beta*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.204'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release
          
      - name: Archive output
        run: |
          mkdir Release
          zip -r Release/bangumi-archive-tool-${{ github.ref_name }}.zip ./bangumi-archive-tool/bin/Release/net8.0/*
          
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'beta'
          name: ${{ github.ref_name }}
          draft: false
          prerelease: true
          files: bangumi-archive-tool-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}