name: Build and Release (Beta)

permissions:
  contents: write

on:
  push:
    branches:
      - beta*
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.204'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release
      
      - name: Read version from VERSION file
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      
      - name: Archive output
        run: |
          mkdir Release
          zip -r Release/bangumi-archive-tool-${{ env.VERSION }}.zip ./bangumi-archive-tool/bin/Release/net8.0/*
          
      - name: Get commit messages
        id: get_commit_messages
        run: echo "COMMIT_MESSAGES=$(git log origin/${{ github.event.before }}..HEAD --pretty=format:'%h %s')" >> $GITHUB_ENV
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: true
          files: Release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}